### ISSUE TITLE
Custom Deserialization for `List`s

### ISSUE THREAD

**Issue by ZekNikZ** [ZekNikZ/CSI3471-Resume-Builder#30]

**Comment by nnazo** [comment]
Turns out when a JSON array is e.g. `"experiences": []` instead of the just not being there or null, it will deserialize (somewhat) correctly (to an `ArrayList` instead of `LinkedList`). So assuming we never have null lists in our actual data (all of our constructors seem to initialize them), a `ListSerializer` should be implemented instead.

This code snippet is from the `TreeTypeAdapter` class in `Gson`, showing that I can't do much about arrays being deserialized as null when are indeed null, aside from not serializing empty lists as null. The last return statement is primarily what I'm referring to.

```
public T read(JsonReader in) throws IOException {
        if (this.deserializer == null) {
            return this.delegate().read(in);
        } else {
            JsonElement value = Streams.parse(in);
            return value.isJsonNull() ? null : this.deserializer.deserialize(value, this.typeToken.getType(), this.context);
        }
}
```

`Gson` is doing the same thing with serialization, so I can only prevent serializing empty Lists as null, and not null lists as null.

However, I have implemented the `ListSerializer` class locally and it appears to be working as intended (preventing `Gson` from serializing empty lists as null).

Please let me know if there are any concerns with doing it this way that should be addressed.
